config/routes.rb
 KakoonaAdportal::Application.routes.draw do
  resources :orders

  resources :products

  resources :kakoona_videos

  resources :campaign_preload_grffks

  resources :campaign_brand_grffks

  resources :ad_campaigns
  match 'load_campaign/:id', to: 'ad_campaigns#load', via: :get
  get "go_simple", to: 'products#go_simple'
  get "go_digital", to: 'products#go_digital'
  get "go_configurable", to: 'products#go_configurable'

  resources :merch_representatives

  resources :merchants

  resources :sessions, only: [:new, :create, :destroy]
  

  root 'dashboard#home'
  
  get 'pspost', to: 's3#new'

  get 'dashboard/about'

  get 'dashboard/future'

  get 'dashboard/contact'
  

  match '/login',   to: 'sessions#new', via: :get
  match '/logout',  to: 'sessions#destroy', via: :delete
  match '/signup',  to: 'merch_representatives#new', via: :get

  match '/products-gallery',   to: 'products#index', via: :get
  match '/videos-gallery',   to: 'kakoona_videos#index', via: :get
  
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :signed_in_user

  def home
  	#@ad_campaigns = AdCampaign.where(merch_representative_id: current_user.id)
	#@ad_campaigns.each do |ad_campaign|
	  #logger.debug "Video Title: #{ad_campaign.vid.title}"
	#end
	@ad_campaigns = current_user.ad_campaigns
  	logger.debug "AD CAMPAIGN COUNT: #{@ad_campaigns.count}"
  
  end

  def about
  end

  def future
  end

  def contact
  end


end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/about.html.erb
<h1>Dashboard#about</h1>
<p>Find me in app/views/statix/about.html.erb</p>

app/views/dashboard/contact.html.erb
<h1>Dashboard#contact</h1>
<p>Find me in app/views/statix/contact.html.erb</p>

app/views/dashboard/future.html.erb
<h1>Dashboard#future</h1>
<p>Find me in app/views/statix/future.html.erb</p>

app/views/dashboard/home.html.erb
    <!-- upper main stats -->
    <div id="main-stats">
        <div class="row stats-row">
            <div class="col-md-6 col-sm-6 merch-subheader">
                <div class="merch-thum">
                    <%= link_to image_tag("logo_hasbro.jpg", alt: "Hasbro", title: "Merchant Info"), "#" , class: 'img-responsive', id: 'merch-logo' %>
                </div>
                <span class="day">Sunday</span>
                <span class="date">
                    February 22, 2015
                </span>
            </div>
            <div class="col-md-2 col-sm-2 merch-subheader">
                <div class="merch-stat">
                    <i class="fa fa-play fa-2x"></i>
                    <span class="stat-label">Total Streams</span>
                    <span class="number">
                        83,789
                    </span>
                </div>
            </div>
            <div class="col-md-2 col-sm-2 merch-subheader">
                <div class="merch-stat">
                    <i class="fa fa-volume-up fa-2x"></i>
                    <span class="stat-label">Total Clicks</span>
                    <span class="number">
                        81,534
                    </span>
                </div>
            </div>
            <div class="col-md-2 col-sm-2 merch-subheader">
                <div class="merch-stat">
                    <i class="fa fa-money fa-2x"></i>
                    <span class="stat-label">Total Purchases</span>
                    <span class="number">
                       2,677
                    </span>
                </div>
            </div>
        </div>
    </div>
    <!-- end upper main stats -->

    <div id="pad-wrapper" class="dashboard" >

        <!-- statistics chart built with jQuery Flot -->
        <div class="row chart">
            <div class="col-md-12">
                <h4 class="clearfix pull-left">
                    Statistics                         
                </h4>
                <div class="btn-group pull-right">
                    <button class="glow left">DAY</button>
                    <button class="glow middle">MONTH</button>
                    <button class="glow right active">YEAR</button>
                </div>
                <div id="legendContainer"></div>
            </div>
            <div class="col-md-12">
                <div id="statsChart"></div>
            </div>
        </div>
        <!-- end statistics chart -->

        
        <div class="table-products section">
            <div class="row head">
                <div class="col-md-10">
                    <i class="fa fa-bullhorn fa-2x"></i><span class="campaigns-subtitle">Current Campaigns</span><span class="campaign-count">(<%= @ad_campaigns.count %>)</span>
                </div>
                <div class="col-md-2 btn-add-campaign">
                    <%= link_to "+ Add A Campaign", new_ad_campaign_path, class:"btn-flat new-product" %>
                </div>
            </div>

            <% @ad_campaigns.each do |ad_campaign| %>

                <!--  start row -->
                <div class="row campaign-row">
                    <div class="col-md-4 col-sm-4 campaign-inst">
                        <div class="campaign-thum">
                            <%= link_to image_tag(ad_campaign.kakoona_video.movie.url(:thum_medium), alt: "Campaign", title: "Campaign Info"), "#" , class: 'img-responsive', id: 'campaign-thum-img' %>
                        </div>
                        <span class="campaign-title">
                            <%= ad_campaign.campaign_title  %>
                        </span>
                        <span class="day">
                            <i class="fa fa-link"></i>
                            <%= link_to "View Details", ad_campaign_path(ad_campaign.id) %>
                        </span>
                    </div>
                    <div class="col-md-2 col-sm-2 campaign-inst">
                        <div class="campaign-stat">
                            <i class="fa fa-play fa-2x"></i>
                            <span class="stat-label">Total Streams</span>
                            <span class="number">
                                83,789
                            </span>
                        </div>
                    </div>
                    <div class="col-md-2 col-sm-2 campaign-inst">
                        <div class="campaign-stat">
                            <i class="fa fa-volume-up fa-2x"></i>
                            <span class="stat-label">Total Clicks</span>
                            <span class="number">
                                81,534
                            </span>
                        </div>
                    </div>
                    <div class="col-md-2 col-sm-2 campaign-inst">
                        <div class="campaign-stat">
                            <i class="fa fa-money fa-2x"></i>
                            <span class="stat-label">Total Purchases</span>
                            <span class="number">
                               2,677
                            </span>
                        </div>
                    </div>
                    <div class="col-md-2 col-sm-2 campaign-inst">
                        <div class="campaign-stat edit">
                            <span class="number"><%= link_to "EDIT PRODUCT", edit_ad_campaign_path(ad_campaign.id) %></span>
                        </div>
                    </div>
                </div>
                <!-- end row -->

            <% end %>





            <ul class="pagination">
                <li><a href="#">&laquo;</a></li>
                <li class="active"><a href="#">1</a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">&raquo;</a></li>
            </ul>
        </div>
        <!-- end table sample -->
    </div>