config/routes.rb
 KakoonaAdportal::Application.routes.draw do
  resources :orders

  resources :products

  resources :kakoona_videos

  resources :campaign_preload_grffks

  resources :campaign_brand_grffks

  resources :ad_campaigns
  match 'load_campaign/:id', to: 'ad_campaigns#load', via: :get
  get "go_simple", to: 'products#go_simple'
  get "go_digital", to: 'products#go_digital'
  get "go_configurable", to: 'products#go_configurable'

  resources :merch_representatives

  resources :merchants

  resources :sessions, only: [:new, :create, :destroy]
  

  root 'dashboard#home'
  
  get 'pspost', to: 's3#new'

  get 'dashboard/about'

  get 'dashboard/future'

  get 'dashboard/contact'
  

  match '/login',   to: 'sessions#new', via: :get
  match '/logout',  to: 'sessions#destroy', via: :delete
  match '/signup',  to: 'merch_representatives#new', via: :get

  match '/products-gallery',   to: 'products#index', via: :get
  match '/videos-gallery',   to: 'kakoona_videos#index', via: :get
  
end

app/models/ad_campaign.rb
class AdCampaign < ActiveRecord::Base
  belongs_to :merch_representative

  #Nested Brand Grffk
  has_one :campaign_brand_grffk, inverse_of: :ad_campaign
  accepts_nested_attributes_for :campaign_brand_grffk, allow_destroy: true

  #Nested Preload Grffk
  has_one :campaign_preload_grffk, inverse_of: :ad_campaign
  accepts_nested_attributes_for :campaign_preload_grffk, allow_destroy: true

  #Nested Kakoona Video
  has_one :kakoona_video, inverse_of: :ad_campaign
  accepts_nested_attributes_for :kakoona_video, allow_destroy: true

  #Nested Product
  has_one :product, inverse_of: :ad_campaign
  accepts_nested_attributes_for :product, allow_destroy: true
  

  def start_date=(date)   
    begin   
      parsed = Date.strptime(date,'%m/%d/%Y %I:%M %p')    
      super parsed    
    rescue    
      date            
    end   
  end    

  def end_date=(date)    
    begin   
      parsed = Date.strptime(date,'%m/%d/%Y %I:%M %p')    
      super parsed    
    rescue    
      date            
    end   
  end
  
end

app/controllers/ad_campaigns_controller.rb
class AdCampaignsController < ApplicationController
  before_action :set_ad_campaign, only: [:show, :edit, :update, :destroy]

  before_action :signed_in_user,
                only: [:edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  #respond_to :json

  # GET /ad_campaigns
  # GET /ad_campaigns.json
  def index
    @ad_campaigns = AdCampaign.all
  end

  # GET /ad_campaigns/1
  # GET /ad_campaigns/1.json
  def show
    @ad_campaign = AdCampaign.find(params[:id])
    #render json: @ad_campaign
    #format.html { redirect_to @ad_campaign }
    #format.json { render :show, status: :created, location: @ad_campaign }
  end

  # GET /load_campaigns/1
  # GET /load_campaigns/1.json
  def load
    @ad_campaign = AdCampaign.find(params[:id])
    @ad_campaign.campaign_plays += 1
    @ad_campaign.save
    render json: @ad_campaign
  end

  # GET /ad_campaigns/new
  def new
    @ad_campaign = AdCampaign.new
    @ad_campaign.build_campaign_brand_grffk
    @ad_campaign.build_campaign_preload_grffk
    @ad_campaign.build_kakoona_video
    @ad_campaign.build_product
    @ad_campaign.product.product_sku_variants.build

    3.times { @ad_campaign.product.product_features.build }
    
  end

  # GET /ad_campaigns/1/edit
  def edit
  end

  # POST /ad_campaigns
  # POST /ad_campaigns.json
  def create
    @ad_campaign = current_user.ad_campaigns.build(ad_campaign_params)

    respond_to do |format|
      if @ad_campaign.save
        
        format.html { redirect_to @ad_campaign, notice: 'Ad campaign was successfully created.' }
        format.json { render :show, status: :created, location: @ad_campaign }
      else
        format.html { render :new }
        format.json { render json: @ad_campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ad_campaigns/1
  # PATCH/PUT /ad_campaigns/1.json
  def update
    respond_to do |format|
      if @ad_campaign.update(ad_campaign_params)
        format.html { redirect_to @ad_campaign, notice: 'Ad campaign was successfully updated.' }
        format.json { render :show, status: :ok, location: @ad_campaign }
      else
        format.html { render :edit }
        format.json { render json: @ad_campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ad_campaigns/1
  # DELETE /ad_campaigns/1.json
  def destroy
    @ad_campaign.destroy
    respond_to do |format|
      format.html { redirect_to ad_campaigns_url, notice: 'Ad campaign was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ad_campaign
      @ad_campaign = AdCampaign.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ad_campaign_params
      #nested_keys = params[:ad_campaign][:product_attributes].fetch(:config_vars,{}).keys
      #logger.debug "AD CAMPAIGN Config Var Keys: #{nested_keys.inspect}"
      params.require(:ad_campaign).permit(:merch_representative_id, :campaign_title, :start_date, :end_date, :slug, :merchant_info_url, 
                                          campaign_brand_grffk_attributes: [ :id, :grffk, :cloud_asset_url ],
                                          campaign_preload_grffk_attributes: [ :id, :grffk, :cloud_asset_url ],
                                          kakoona_video_attributes: [:id, :movie, :length, :title, :description, :cloud_asset_url, :selected_thum  ],
                                          product_attributes: [:id, :product_type, :name, :grffk, :cloud_asset_url, :download_url,
                                            product_sku_variants_attributes: [:id, :sku, :feature_set, :description, :price, :in_stock, :gal_grffk01, :cloud_asset01_url, :gal_grffk02, :cloud_asset02_url, :gal_grffk03, :cloud_asset03_url, :gal_grffk04, :cloud_asset04_url, :gal_grffk05, :cloud_asset05_url, :gal_grffk06, :cloud_asset06_url, :_destroy ],
                                            product_features_attributes:[:id, :ftr_name, :ftr_detail, :_destroy, product_feature_values_attributes: [:id, :value, :abbreviation, :_destroy]]])
    end

    def correct_user
      @ad_campaign = current_user.ad_campaigns.find_by(id: params[:id])
      redirect_to root_url if @ad_campaign.nil?
    end
end

app/helpers/ad_campaigns_helper.rb
module AdCampaignsHelper
end

app/views/ad_campaigns/_form.html.erb
<%= form_for(@ad_campaign, multipart: true, html: { class: "direct-upload"}) do |f| %>
  <% if @ad_campaign.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ad_campaign.errors.count, "error") %> prohibited this ad_campaign from being saved:</h2>

      <ul>
      <% @ad_campaign.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div class="col-md-8 col-sm-12">
    <div class="form-group">  
      <%= f.text_field :campaign_title, autofocus: true, placeholder: 'Your Campaign Title'  %>
    </div>
    <div class="form-group">
      <!--<span>Campaign Address: </span><span>https://www.kakoona.com/v1/campaigns/load_cocoon/38746837</span>-->
    </div>
    <div class="row">
      <div class="col-md-6 col-sm-12">
        <div class="form-group">
          <%= f.label :start_date %><br>
          <div class='input-group date' id='start_datetimepicker'>
              <%= f.text_field :start_date, class: "form-control", value: date_for_edit(@ad_campaign.start_date) %>
              <span class="input-group-addon">
                  <span class="glyphicon glyphicon-calendar"></span>
              </span>
          </div> 
        </div> 
      </div>
      <div class="col-md-6 col-sm-12">
        <div class="form-group">
          <%= f.label :end_date %><br>
          <div class='input-group date' id='end_datetimepicker'>
              <%= f.text_field :end_date, class: "form-control", value: date_for_edit(@ad_campaign.end_date) %>
              <span class="input-group-addon">
                  <span class="glyphicon glyphicon-calendar"></span>
              </span>
          </div> 
        </div> 
      </div>
      <div class="col-md-12 col-sm-12">
        <div class="form-group">
          <%= f.text_field :merchant_info_url, placeholder: 'www.hasbro.com/new-hotness'  %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-3 col-sm-12 text-center">
      <div class="grffk-wrap">
          <%= f.fields_for :campaign_brand_grffk do |brand_grffk_form| %>
            <%= render 'up_brand_grffk', up: brand_grffk_form %>
          <% end %>
      </div>
      <p>Upload Your Brand Graphic</p>
  </div>
</div>
<div class="separator"></div>

<%= f.fields_for :kakoona_video do |video_form| %>
  <%= render 'kakoona_videos/upload', vid: video_form %>
<% end %>

<div class="separator"></div>

<%= f.fields_for :product do |product_form| %>
  <%= render 'products/product_fields', prod: product_form %>
<% end %>
  

  <div class="actions">
    <div class="form-buttons">
      <div class="button">
        <%= f.submit "Save", class: "kakoona-submit" %>
      </div>
    </div>
  </div>

<% end %>

app/views/ad_campaigns/_up_brand_grffk.html.erb
<fieldset class: 'brand_grffk-fields' id: 'brand_grffk-fields'>
    <%= up.label :grffk, capture { %>
	  <%= image_tag "default_uploadgrffk_btn.png", alt: "Upload Pad", title: "campaign brand logo" , class: 'img-responsive center-block', id: 'brand_prevu' %>
	<% } %>
	<%= up.file_field :grffk, accept: 'image/png,image/gif,image/jpeg,image/jpg' %>
	<%= up.hidden_field :cloud_asset_url, value: "upload" %>
</fieldset>

app/views/ad_campaigns/edit.html.erb
<%= render 'layouts/upper_main' %>
<h1> EDIT MODE </h1>
<div id="pad-wrapper" class="logic-edit">
    <%= render 'form' %>
    <%= link_to 'Back', root_path %>
</div>

app/views/ad_campaigns/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ad Campaigns</h1>

<table>
  <thead>
    <tr>
      <th>Campaign title</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Slug</th>
      <th>Merchant info url</th>
      <th>Campaign reach</th>
      <th>Campaign plays</th>
      <th>Clickthru</th>
      <th>Campaign price</th>
      <th>Merchant</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ad_campaigns.each do |ad_campaign| %>
      <tr>
        <td><%= ad_campaign.campaign_title %></td>
        <td><%= ad_campaign.start_date %></td>
        <td><%= ad_campaign.end_date %></td>
        <td><%= ad_campaign.slug %></td>
        <td><%= ad_campaign.merchant_info_url %></td>
        <td><%= ad_campaign.campaign_reach %></td>
        <td><%= ad_campaign.campaign_plays %></td>
        <td><%= ad_campaign.clickthru %></td>
        <td><%= ad_campaign.campaign_price %></td>
        <td><%= ad_campaign.merchant %></td>
        <td><%= link_to 'Show', ad_campaign %></td>
        <td><%= link_to 'Edit', edit_ad_campaign_path(ad_campaign) %></td>
        <td><%= link_to 'Destroy', ad_campaign, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ad campaign', new_ad_campaign_path %>

app/views/ad_campaigns/new.html.erb
<%= render 'layouts/upper_main' %>
<div id="pad-wrapper">
    <%= render 'form' %>
    <%= link_to 'Back', ad_campaigns_path %>
</div>

app/views/ad_campaigns/show.html.erb
<!-- Pad Wrapper -->
<div id="pad-wrapper" class="show-ad-campaigns">

  <!-- Content -->
  <div class="row">                        
    <div class="col-sm-12 col-centered text-center">
      <h3><%= @ad_campaign.campaign_title %></h3>

      <h4>http://www.kakoona.com/view/xxxx</h4>
      
      <% if @ad_campaign.kakoona_video.movie_processing? %>
        <div class="grffk-wrap">
          <%= image_tag("processing.gif", alt: "processing", title: @ad_campaign.campaign_title) %>
        </div>
        <p>
          <strong>Status: </strong>PROCESSING
        </p>
      <% else %>
        <div class="grffk-wrap">
          <%= image_tag(@ad_campaign.kakoona_video.movie.url(:thum_medium), alt: "video screenshot", title: @ad_campaign.campaign_title) %>
        </div> 
        <p>
          <strong>Status: </strong>ACTIVE
        </p>
      <% end %>
     
      <p>
        <strong>Start date:</strong>
        <%= date_for_display(@ad_campaign.start_date) %>
      </p>

      <p>
        <strong>End date:</strong>
        <%= date_for_display(@ad_campaign.end_date) %>
      </p>
      <p>
        <strong>Merchant Info URL:</strong>
        <%= @ad_campaign.merchant_info_url %>
      </p>

      <p>
        <strong>Campaign plays:</strong>
        <%= @ad_campaign.campaign_plays %>
      </p>

      <p>
        <strong>Click Interactions:</strong>
        <%= @ad_campaign.clickthru %>
      </p>

      <p>
        <strong>Created by:</strong>
        <%= @ad_campaign.merch_representative.screen_name %> 
      </p>

      <%= link_to "EDIT", edit_ad_campaign_path(@ad_campaign), class:"btn-flat btn-pad-small" %>

    </div>
  </div>

</div>
<!-- /Pad Wrapper -->