config/routes.rb
 KakoonaAdportal::Application.routes.draw do
  resources :orders

  resources :products

  resources :kakoona_videos

  resources :campaign_preload_grffks

  resources :campaign_brand_grffks

  resources :ad_campaigns
  match 'load_campaign/:id', to: 'ad_campaigns#load', via: :get
  get "go_simple", to: 'products#go_simple'
  get "go_digital", to: 'products#go_digital'
  get "go_configurable", to: 'products#go_configurable'

  resources :merch_representatives

  resources :merchants

  resources :sessions, only: [:new, :create, :destroy]
  

  root 'dashboard#home'
  
  get 'pspost', to: 's3#new'

  get 'dashboard/about'

  get 'dashboard/future'

  get 'dashboard/contact'
  

  match '/login',   to: 'sessions#new', via: :get
  match '/logout',  to: 'sessions#destroy', via: :delete
  match '/signup',  to: 'merch_representatives#new', via: :get

  match '/products-gallery',   to: 'products#index', via: :get
  match '/videos-gallery',   to: 'kakoona_videos#index', via: :get
  
end

app/models/campaign_preload_grffk.rb
class CampaignPreloadGrffk < ActiveRecord::Base
  belongs_to :ad_campaign, inverse_of: :campaign_preload_grffk

  has_attached_file :grffk, 
  					:styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :grffk, :content_type => /\Aimage\/.*\Z/

  process_in_background :grffk

  before_create :set_grffk_attributes

  after_create :queue_finalize_and_cleanup

  after_find :verify_asset_loc


  S3_BUCKET =  AWS::S3.new.buckets[ENV['S3_BUCKET']]


  def self.finalize_and_cleanup(id)
    preload_grffk = CampaignPreloadGrffk.find(id)
    
    #PaperClip Path Process
    paperclip_file_path = preload_grffk.grffk.path
    paperclip_no_slash = paperclip_file_path[1..-1]

    #Uploaded Asset Process ****
    #Extracts raw filename 
    #Creates unescaped URL with encode filename
    upload_url = CGI.unescape(preload_grffk.cloud_asset_url)
    file_name = upload_url.split("/").last
    upload_info = upload_url.split("/")
    upload_info.pop
    full_upload_url = upload_info.join("/") + ("/") + URI.encode(file_name)

    #Uploaded Asset Process ****
    #Convert URL to URI Object 
    #replace URL-encoded filename with Raw filename
    cloud_asset_url_data = URI.parse(full_upload_url)
    cloud_asset_no_slash = cloud_asset_url_data.path[1..-1]
    cloud_asset_info = cloud_asset_no_slash.split("/")
    cloud_asset_info.pop
    full_asset_path = cloud_asset_info.join("/") + ("/") + file_name

    logger.debug "SOURCE PATH::  #{full_asset_path}" 

    logger.debug "PAPERCLIP PATH::  #{paperclip_no_slash}"

    #S3_BUCKET.objects[paperclip_no_slash].copy_from(full_asset_path, {acl: 'public-read'})

    obj = S3_BUCKET.objects[full_asset_path]
    file = Paperclip.io_adapters.for(obj.public_url)
    preload_grffk.grffk = file
    preload_grffk.grffk_content_type = Paperclip::ContentTypeDetector.new(file.path).detect

    preload_grffk.save

    #Delete Direct Uploaded Temp Asset
    #S3_BUCKET.objects[full_asset_path].delete
  end
  
  protected
  
  # Optional: Set attachment attributes from the direct upload instead of original upload callback params
  # @note Retry logic handles occasional S3 "eventual consistency" lag.
  def set_grffk_attributes
    tries ||= 5

      #Uploaded Asset Process ****
      #Extracts raw filename 
      #Creates unescaped URL with encode filename
      upload_url = CGI.unescape(cloud_asset_url)
      file_name = upload_url.split("/").last
      upload_info = upload_url.split("/")
      upload_info.pop
      full_upload_url = upload_info.join("/") + ("/") + URI.encode(file_name)

      #Uploaded Asset Process ****
      #Convert URL to URI Object 
      #replace URL-encoded filename with Raw filename
      cloud_asset_url_data = URI.parse(full_upload_url)
      cloud_asset_no_slash = cloud_asset_url_data.path[1..-1]
      cloud_asset_info = cloud_asset_no_slash.split("/")
      cloud_asset_info.pop
      full_asset_path = cloud_asset_info.join("/") + ("/") + file_name

      direct_upload_head = S3_BUCKET.objects[full_asset_path].head 

      self.grffk_file_name      = file_name
      self.grffk_file_size      = direct_upload_head.content_length
      self.grffk_content_type   = direct_upload_head.content_type
      self.grffk_updated_at     = direct_upload_head.last_modified
  rescue AWS::S3::Errors::NoSuchKey => e
    tries -= 1
    if tries > 0
      sleep(3)
      retry
    else
      raise e
    end
  end

  # Queue final file processing
  def queue_finalize_and_cleanup
    CampaignPreloadGrffk.delay(queue: "grffk_process").finalize_and_cleanup(id)
  end

  def verify_asset_loc
    logger.debug "****** VERIFYING PRELOAD GRAPHIC ASSET LOCATION ******* "

    if self.grffk_processing == false
      logger.debug "PRELOAD GRAPHIC HAS BEEN PROCESSED"
      if self.cloud_asset_url != self.grffk.url(:medium, timestamp: false)
        self.cloud_asset_url = self.grffk.url(:medium, timestamp: false)
        self.save
        logger.debug "******** NEW PRELOAD GRAPHIC ASSET LOCATIONS SAVED ******** "
      else
        logger.debug "******** PERMANENT PRELOAD GRAPHIC ASSET LOCATION VERIFIED ******** "
      end
    end
  end

end

app/controllers/campaign_preload_grffks_controller.rb
class CampaignPreloadGrffksController < ApplicationController
  #before_action :set_campaign_preload_grffk, only: [:show, :edit, :update, :destroy]

  # POST /campaign_preload_grffks
  # POST /campaign_preload_grffks.json
  def create
    @campaign_preload_grffk = CampaignPreloadGrffk.new(campaign_preload_grffk_params)

    respond_to do |format|
      if @campaign_preload_grffk.save
        format.html { redirect_to @campaign_preload_grffk, notice: 'Campaign preload grffk was successfully created.' }
        format.json { render :show, status: :created, location: @campaign_preload_grffk }
      else
        format.html { render :new }
        format.json { render json: @campaign_preload_grffk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campaign_preload_grffks/1
  # PATCH/PUT /campaign_preload_grffks/1.json
  def update
    @ad_campaign = current_ad_campaign.find(params[:ad_campaign_id])
    @preload_grffk = @ad_campaign.preload_brand_grffk.find(params[:id])

    respond_to do |format|
      if @preload_grffk.update(campaign_preload_grffk_params)
        flash[:success]= 'Campaign brand grffk was successfully updated.'
      else
        flash[:error] = @preload_grffk.errors.full_messages[0] if @preload_grffk.errors.count > 0
      end
    end
  end

  # DELETE /campaign_preload_grffks/1
  # DELETE /campaign_preload_grffks/1.json
  def destroy
    @ad_campaign = current_ad_campaign.find(params[:ad_campaign_id])
    @preload_grffk = @ad_campaign.campaign_preload_grffk.find(params[:id])

    if @preload_grffk.destroy
        flash[:success]= 'Campaign Preload Graphic destroyed'
    else
      flash[:error] = @preload_grffk.errors.full_messages[0] if @preload_grffk.errors.count > 0
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campaign_preload_grffk
      @campaign_preload_grffk = CampaignPreloadGrffk.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def campaign_preload_grffk_params
      params.require(:campaign_preload_grffk).permit(:ad_campaign_id, :grffk, :cloud_asset_url )
    end
end

app/helpers/campaign_preload_grffks_helper.rb
module CampaignPreloadGrffksHelper
end

app/views/campaign_preload_grffks/_form.html.erb
<%= form_for(@campaign_preload_grffk) do |f| %>
  <% if @campaign_preload_grffk.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@campaign_preload_grffk.errors.count, "error") %> prohibited this campaign_preload_grffk from being saved:</h2>

      <ul>
      <% @campaign_preload_grffk.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ad_campaign_id %><br>
    <%= f.text_field :ad_campaign_id %>
  </div>
  <div class="field">
    <%= f.label :raw_file_name %><br>
    <%= f.text_field :raw_file_name %>
  </div>
  <div class="field">
    <%= f.label :meta_description %><br>
    <%= f.text_field :meta_description %>
  </div>
  <div class="field">
    <%= f.label :file_type %><br>
    <%= f.text_field :file_type %>
  </div>
  <div class="field">
    <%= f.label :grffk_url %><br>
    <%= f.text_field :grffk_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/campaign_preload_grffks/edit.html.erb
<h1>Editing Campaign Preload Grffk</h1>

<%= render 'form' %>

<%= link_to 'Show', @campaign_preload_grffk %> |
<%= link_to 'Back', campaign_preload_grffks_path %>

app/views/campaign_preload_grffks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Campaign Preload Grffks</h1>

<table>
  <thead>
    <tr>
      <th>Ad campaign</th>
      <th>Raw file name</th>
      <th>Meta description</th>
      <th>File type</th>
      <th>Grffk url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @campaign_preload_grffks.each do |campaign_preload_grffk| %>
      <tr>
        <td><%= campaign_preload_grffk.ad_campaign %></td>
        <td><%= campaign_preload_grffk.raw_file_name %></td>
        <td><%= campaign_preload_grffk.meta_description %></td>
        <td><%= campaign_preload_grffk.file_type %></td>
        <td><%= campaign_preload_grffk.grffk_url %></td>
        <td><%= link_to 'Show', campaign_preload_grffk %></td>
        <td><%= link_to 'Edit', edit_campaign_preload_grffk_path(campaign_preload_grffk) %></td>
        <td><%= link_to 'Destroy', campaign_preload_grffk, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Campaign preload grffk', new_campaign_preload_grffk_path %>

app/views/campaign_preload_grffks/new.html.erb
<h1>New Campaign Preload Grffk</h1>

<%= render 'form' %>

<%= link_to 'Back', campaign_preload_grffks_path %>

app/views/campaign_preload_grffks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ad campaign:</strong>
  <%= @campaign_preload_grffk.ad_campaign %>
</p>

<p>
  <strong>Raw file name:</strong>
  <%= @campaign_preload_grffk.raw_file_name %>
</p>

<p>
  <strong>Meta description:</strong>
  <%= @campaign_preload_grffk.meta_description %>
</p>

<p>
  <strong>File type:</strong>
  <%= @campaign_preload_grffk.file_type %>
</p>

<p>
  <strong>Grffk url:</strong>
  <%= @campaign_preload_grffk.grffk_url %>
</p>

<%= link_to 'Edit', edit_campaign_preload_grffk_path(@campaign_preload_grffk) %> |
<%= link_to 'Back', campaign_preload_grffks_path %>