config/routes.rb
 KakoonaAdportal::Application.routes.draw do
  resources :orders

  resources :products

  resources :kakoona_videos

  resources :campaign_preload_grffks

  resources :campaign_brand_grffks

  resources :ad_campaigns
  match 'load_campaign/:id', to: 'ad_campaigns#load', via: :get
  get "go_simple", to: 'products#go_simple'
  get "go_digital", to: 'products#go_digital'
  get "go_configurable", to: 'products#go_configurable'

  resources :merch_representatives

  resources :merchants

  resources :sessions, only: [:new, :create, :destroy]
  

  root 'dashboard#home'
  
  get 'pspost', to: 's3#new'

  get 'dashboard/about'

  get 'dashboard/future'

  get 'dashboard/contact'
  

  match '/login',   to: 'sessions#new', via: :get
  match '/logout',  to: 'sessions#destroy', via: :delete
  match '/signup',  to: 'merch_representatives#new', via: :get

  match '/products-gallery',   to: 'products#index', via: :get
  match '/videos-gallery',   to: 'kakoona_videos#index', via: :get
  
end

app/models/merch_representative.rb
class MerchRepresentative < ActiveRecord::Base 
  belongs_to :merchant
  validates :merchant_id, presence: true

  before_save { self.email = email.downcase }

  before_create :create_remember_token
  validates :first_name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }

  #Nested Avatar
  has_one :avatar_grffk, inverse_of: :merch_representative
  accepts_nested_attributes_for :avatar_grffk, allow_destroy: true

  #Ad Campaigns
  has_many :ad_campaigns

  #def avatar_for_form
    #avi = avatar_grffk.where(merch_representative_id: id)
    #avi.any? ? avi : avatar_grffk.build
  #end

  def MerchRepresentative.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def MerchRepresentative.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end


  private

    def create_remember_token
      self.remember_token = MerchRepresentative.digest(MerchRepresentative.new_remember_token)
    end
end

app/controllers/merch_representatives_controller.rb
class MerchRepresentativesController < ApplicationController
  before_action :set_merch_representative, only: [:show, :edit, :update, :destroy]

  before_action :signed_in_user,
                only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: [:index, :destroy]

  # GET /merch_representatives
  # GET /merch_representatives.json
  def index
    @merch_representatives = MerchRepresentative.all
  end

  # GET /merch_representatives/1
  # GET /merch_representatives/1.json
  def show
    #@merch_representative.build_avatar_grffk
  end

  # GET /merch_representatives/new
  def new
    @merch_representative = MerchRepresentative.new
    @merch_representative.build_avatar_grffk
  end

  # GET /merch_representatives/1/edit
  def edit
  end

  # POST /merch_representatives
  # POST /merch_representatives.json
  def create
    @merch_representative = MerchRepresentative.new(merch_representative_params)

    respond_to do |format|
      if @merch_representative.save

        format.html { redirect_to login_path, notice: 'Merch representative was successfully created.  Now Sign in!' }
        format.json { render :show, status: :created, location: @merch_representative }
      else
        format.html { render :new }
        format.json { render json: @merch_representative.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /merch_representatives/1
  # PATCH/PUT /merch_representatives/1.json
  def update
    respond_to do |format|
      if @merch_representative.update(merch_representative_params)
        format.html { redirect_to @merch_representative, notice: 'Merch representative was successfully updated.' }
        format.json { render :show, status: :ok, location: @merch_representative }
      else
        format.html { render :edit }
        format.json { render json: @merch_representative.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /merch_representatives/1
  # DELETE /merch_representatives/1.json
  def destroy
    @merch_representative.destroy
    respond_to do |format|
      format.html { redirect_to merch_representatives_url, notice: 'Merch representative was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_merch_representative
      @merch_representative = MerchRepresentative.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def merch_representative_params
      params.require(:merch_representative).permit(:merchant_id, :email, :screen_name, :first_name, :middle_name, :last_name, :phone, :team_role, :rep_about, :is_active, :auth_token, :last_session_time, :last_session_ip, :password, :password_confirmation, :admin, avatar_grffk_attributes: [ :id, :grffk, :cloud_asset_url ])
    end

    def correct_user
      @merch_representative = MerchRepresentative.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
    
    def admin_user
      @merch_representative = MerchRepresentative.find(session[:merch_representative_id])
      redirect_to(root_path) if !current_user.admin? || current_user?(@user)
    end

end

app/views/merch_representatives/_avatar_grffk.html.erb
<% if @merch_representative.avatar_grffk.cloud_asset_url.present? %>
  <%= image_tag @merch_representative.avatar_grffk.cloud_asset_url, alt: "Merch Rep Avi", title: @merch_representative.screen_name , class: 'avatar img-circle img-responsive', id:'avatar_prevu' %>
<% end %>

app/views/merch_representatives/_upload.html.erb
<fieldset class: 'avatar_grffk-fields' id: 'avatar_grffk-fields'>
	<%= avi.label :grffk, capture { %>
	  <%= image_tag "default_uploadgrffk_btn.png", alt: "Brand Graphic", title: "campaign brand logo" , class: 'img-responsive center-block', id:'avatar_prevu' %>
	<% } %>
	<%= avi.file_field :grffk, accept: 'image/png,image/gif,image/jpeg, image/jpg' %>
	<%= avi.hidden_field :cloud_asset_url, value: "upload" %>
</fieldset>

app/views/merch_representatives/edit.html.erb
<h1>Editing Merch Representative</h1>

<div class="row">
	  <div class="span6 offset3">
	  	<div class='formNewEntity'>
	  		<div class='form-content'>

				<h1>Sign up</h1>
			    <%= form_for(@merch_representative, multipart: true, html: { class: "direct-upload"}) do |f| %>
			      <%= render 'sessions/error_messages', object: f.object %>

			     <div class="row display-table">
					<div class="col-md-3 col-xs-12 display-cell text-center grffk-bottom30 grffk-wrap">
					 <%= f.fields_for :avatar_grffk do |avatar_for_form| %>
					 		<%= render 'upload', avi: avatar_for_form %>
					 <% end %>
					</div>
				 </div>
				 

				 <% sys_merchants = [['Abercrombie & Fitch', 1], ['American Eagle', 2], ['Bose', 3], ['Hasbro', 4],] %>
			      <%= f.select(:merchant_id, options_for_select(sys_merchants), {include_blank: "Select Your Merchant"}, {'data-toggle' => "select", required: "true", autofocus: "true", class: "kakoona-select"})%>

			      <%= f.text_field :first_name, autofocus: true, placeholder: 'First Name' %>

			      <%= f.text_field :last_name, autofocus: true, placeholder: 'Last Name' %>

			      <%= f.text_field :email, autofocus: true, placeholder: 'Email' %>

			      <%= f.text_field :phone, autofocus: true, value: '312.555.5555', placeholder: 'Phone' %>

			      <%= f.hidden_field :team_role, value: 'representative' %>
			      <%= f.hidden_field :is_active, value: 1 %>

			      <%= f.text_field :screen_name, autofocus: true, placeholder: 'ScreenName' %>

			      <%= f.password_field :password, autofocus: true, placeholder: 'password' %>

			      <%= f.password_field :password_confirmation, autofocus: true, placeholder: 'confirm password' %>

			      <%= f.hidden_field :admin, value: 0 %>
			      
				  <div class="form-buttons">
	                <div class="button">
			      		<%= f.submit "Register", class: "kakoona-submit" %>
			      	</div>
			      	<%= link_to 'Cancel', merch_representative_path(current_user.id) %>
			      </div>
			    <% end %>

			</div>
		</div>
	  </div>
	</div>

app/views/merch_representatives/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Merch Representatives</h1>

<table>
  <thead>
    <tr>
      <th>Merchant</th>
      <th>Email</th>
      <th>Screen name</th>
      <th>First name</th>
      <th>Middle name</th>
      <th>Last name</th>
      <th>Phone</th>
      <th>Team role</th>
      <th>Rep about</th>
      <th>Is active</th>
      <th>Auth token</th>
      <th>Last session time</th>
      <th>Last session ip</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @merch_representatives.each do |merch_representative| %>
      <tr>
        <td><%= merch_representative.merchant.id %></td>
        <td><%= merch_representative.email %></td>
        <td><%= merch_representative.screen_name %></td>
        <td><%= merch_representative.first_name %></td>
        <td><%= merch_representative.middle_name %></td>
        <td><%= merch_representative.last_name %></td>
        <td><%= merch_representative.phone %></td>
        <td><%= merch_representative.team_role %></td>
        <td><%= merch_representative.rep_about %></td>
        <td><%= merch_representative.is_active %></td>
        <td><%= merch_representative.auth_token %></td>
        <td><%= merch_representative.last_session_time %></td>
        <td><%= merch_representative.last_session_ip %></td>
        <td><%= link_to 'Show', merch_representative %></td>
        <td><%= link_to 'Edit', edit_merch_representative_path(merch_representative) %></td>
        <td><%= link_to 'Destroy', merch_representative, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Merch representative', new_merch_representative_path %>

app/views/merch_representatives/new.html.erb
<% provide(:title, 'Become a Representative') %>
<div class="container">
	<div class="row">
	  <div class="span6 offset3">
	  	<div class='formNewEntity'>
	  		<div class='form-content'>

				<h1>Sign up</h1>
			    <%= form_for(@merch_representative, multipart: true, html: { class: "direct-upload"}) do |f| %>
			      <%= render 'sessions/error_messages', object: f.object %>

			     <div class="row display-table">
					<div class="col-md-3 col-xs-12 display-cell text-center grffk-bottom30 grffk-wrap">
					 <%= f.fields_for :avatar_grffk do |avatar_for_form| %>
					 		<%= render 'upload', avi: avatar_for_form %>
					 <% end %>
					</div>
				 </div>
				 

				 <% sys_merchants = [['Abercrombie & Fitch', 1], ['American Eagle', 2], ['Bose', 3], ['Hasbro', 4]] %>
			      <%= f.select(:merchant_id, options_for_select(sys_merchants), {include_blank: "Select Your Merchant"}, {'data-toggle' => "select", required: "true", autofocus: "true", class: "kakoona-select"})%>

			      <%= f.text_field :first_name, autofocus: true, placeholder: 'First Name' %>

			      <%= f.text_field :last_name, autofocus: true, placeholder: 'Last Name' %>

			      <%= f.text_field :email, autofocus: true, placeholder: 'Email' %>

			      <%= f.text_field :phone, autofocus: true, value: '312.555.5555', placeholder: 'Phone' %>

			      <%= f.hidden_field :team_role, value: 'representative' %>
			      <%= f.hidden_field :is_active, value: 1 %>

			      <%= f.text_field :screen_name, autofocus: true, placeholder: 'ScreenName' %>

			      <%= f.password_field :password, autofocus: true, placeholder: 'password' %>

			      <%= f.password_field :password_confirmation, autofocus: true, placeholder: 'confirm password' %>

			      <%= f.hidden_field :admin, value: 0 %>
			      
				  <div class="form-buttons">
	                <div class="button">
			      		<%= f.submit "Register", class: "kakoona-submit" %>
			      	</div>
			      </div>
			    <% end %>

			</div>
		</div>
	  </div>
	</div>
</div>

app/views/merch_representatives/show.html.erb
<div id="pad-wrapper">
  <div class="row">
    
    <!-- avatar column -->
    <div class="col-md-3 col-md-offset-1 avatar-box">
        <div class="personal-image">
            <%= render 'avatar_grffk' %>
            <p>Upload a different photo...</p>
            <!--<input type="file" />-->
        </div>
    </div>

    <!-- edit form column -->
    <div class="col-md-7 personal-info">
        <div class="alert alert-info">
            <p id="notice">
              <i class="fa fa-lightbulb"></i>
              <%= notice %>
            </p>
        </div>
        <h5 class="personal-title">Personal info</h5>

        <form class="form-horizontal" role="form">
            <div class="form-group">
                <label class="col-lg-2 control-label">Screen Name:</label>
                <div class="col-lg-8">
                    <%= @merch_representative.screen_name %>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-2 control-label">First name:</label>
                <div class="col-lg-8">
                    <%= @merch_representative.first_name %>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-2 control-label">Last name:</label>
                <div class="col-lg-8">
                    <%= @merch_representative.last_name %>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-2 control-label">Merchant:</label>
                <div class="col-lg-8">
                    <%= @merch_representative.merchant_id %>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-2 control-label">Email:</label>
                <div class="col-lg-8">
                    <%= @merch_representative.email %>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-2 control-label">Time Zone:</label>
                <div class="col-lg-8">
                    <div class="ui-select">
                        <select id="user_time_zone" name="user[time_zone]">
                            <option value="Hawaii">(GMT-10:00) Hawaii</option>
                            <option value="Alaska">(GMT-09:00) Alaska</option>
                            <option value="Pacific Time (US &amp; Canada)">(GMT-08:00) Pacific Time (US &amp; Canada)</option>
                            <option value="Arizona">(GMT-07:00) Arizona</option>
                            <option value="Mountain Time (US &amp; Canada)">(GMT-07:00) Mountain Time (US &amp; Canada)</option>
                            <option value="Central Time (US &amp; Canada)" selected="selected">(GMT-06:00) Central Time (US &amp; Canada)</option>
                            <option value="Eastern Time (US &amp; Canada)">(GMT-05:00) Eastern Time (US &amp; Canada)</option>
                            <option value="Indiana (East)">(GMT-05:00) Indiana (East)</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-2 control-label">Team Role:</label>
                <div class="col-lg-8">
                    <%= @merch_representative.team_role %>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-2 control-label">Bio:</label>
                <div class="col-lg-8">
                    <p><%= @merch_representative.rep_about %></p>
                </div>
            </div>
            <!--
            <div class="form-group">
                <label class="col-lg-2 control-label">Password:</label>
                <div class="col-lg-8">
                    <input class="form-control" type="password" value="blablablabla" />
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-2 control-label">Confirm password:</label>
                <div class="col-lg-8">
                    <input class="form-control" type="password" value="blablablabla" />
                </div>
            </div>-->
            <div class="actions">
                <%= link_to 'Edit', edit_merch_representative_path(@merch_representative) %>
            </div>
        </form>
    </div>

  </div>

</div>